from django.contrib import admin
from .models import Category,SubCategory, Product,ProductReview, Order, OrderItem, OrderHistory, Cart, Inventory, ShippingMethod, PaymentMethod, Payment, Invoice, Promotion, DiscountCoupon, DiscountRule, Feedback, NewsletterSubscriber, BlogPost, ContactMessage, BannerAdvertisement, FAQ, ReturnRequest, GiftCard, Wishlist, ProductPhoto, ShippingAddress, Refund

admin.site.register(Category)
admin.site.register(SubCategory)
admin.site.register(Product)
admin.site.register(ProductReview)
admin.site.register(Order)
admin.site.register(OrderItem)
admin.site.register(OrderHistory)
admin.site.register(Cart)
admin.site.register(Inventory)
admin.site.register(ShippingMethod)
admin.site.register(PaymentMethod)
admin.site.register(Payment)
admin.site.register(Invoice)
admin.site.register(Promotion)
admin.site.register(DiscountCoupon)
admin.site.register(DiscountRule)
admin.site.register(Feedback)
admin.site.register(NewsletterSubscriber)
admin.site.register(BlogPost)
admin.site.register(ContactMessage)
admin.site.register(BannerAdvertisement)
admin.site.register(FAQ)
admin.site.register(ReturnRequest)
admin.site.register(GiftCard)
admin.site.register(Wishlist)
admin.site.register(ProductPhoto)
admin.site.register(ShippingAddress)
admin.site.register(Refund)
